### ISSUE TITLE
The library is not working on ASP.NET MVC 5 targeted 4.6.1  .NET

### ISSUE THREAD

**Issue by YakupIpek** [louislouw/Louw.PublicSuffix#1]
I am trying to use this library in ASP.NET MVC 5 which is targeted 4.6.1 instead 4.5.2 and it doesn't return any result, doesn't throw exception and always in pause mode. 

What can cause this ?

**Comment by louislouw** [comment]
Hi. Maybe post the snippet of code you use to check domain. also, the specific domain you are trying to check.

**Comment by YakupIpek** [comment]
There is something probably wrong on dependencies. You will see it very easily if you are able to test it.

**Comment by louislouw** [comment]
Ok, was able to duplicate. Problem seems to be with cached rule provider. Will fix soon

**Comment by louislouw** [comment]
Fixed. Please try latest release.

**Comment by louislouw** [comment]
One more update. I went ahead and made library async as the provider really has async methods.
Also, CachedTldRuleProvider was renamed (but you can still use old class name)

So here is example code for how to use it now:
(I just added code to standard About() method in Home controller)
`public async Task<ActionResult> About()
        {
            var domainParser = new DomainParser(new WebTldRuleProvider());
            var domainInfo = await domainParser.ParseAsync("sub.test.co.uk");
            ViewBag.Message = "Domain: "+ domainInfo.RegistrableDomain;

            return View();
        }`

**Comment by YakupIpek** [comment]
Hi I have been able test it and it seems works fine but please don't make this library async because only initialization logic can advantage of async and after that there is no advantage of async. In my opinion parsing methods should not be async.

**Comment by louislouw** [comment]
Yip, I fully agree with you. I've been thinking about it a lot and it bugs me as well. I'm trying to come up with solution where you get the best of both worlds. I'm leaning towards a factory that initializes async, but object returned only has sync methods and is also immutable.
